Class {
	#name : 'AoC24Day09',
	#superclass : 'Object',
	#category : 'AdventOfCode2024',
	#package : 'AdventOfCode2024'
}

{ #category : 'examples' }
AoC24Day09 class >> part1 [

	^ AoC24 inputDay09 readStreamDo: [ :s | self part1: s ]
]

{ #category : 'examples' }
AoC24Day09 class >> part1: stream [


]

{ #category : 'examples' }
AoC24Day09 class >> part2 [

	^ AoC24 inputDay09 readStreamDo: [ :s | self part2: s ]
]

{ #category : 'examples' }
AoC24Day09 class >> part2: stream [


]
