Class {
	#name : 'AoC24Day08',
	#superclass : 'Object',
	#category : 'AdventOfCode2024',
	#package : 'AdventOfCode2024'
}

{ #category : 'examples' }
AoC24Day08 class >> part1 [

	^ AoC24 inputDay08 readStreamDo: [ :s | self part1: s ]
]

{ #category : 'examples' }
AoC24Day08 class >> part1: stream [
]

{ #category : 'examples' }
AoC24Day08 class >> part2 [

	^ AoC24 inputDay08 readStreamDo: [ :s | self part2: s ]
]

{ #category : 'examples' }
AoC24Day08 class >> part2: stream [
]
